### ISSUE TITLE
Exposed Potential private key (.asc)

### ISSUE THREAD

**Issue by ikaustubhk** [UI-FASILKOM-OS/os201#104]
Potential security breach. See /UAS/aceyoga/0004-TUGAS-PAS1.txt.asc

**Comment by skycruiser8** [comment]
Hello!

Thank your for raising this issue. Per the instructions of the "final term exam", the .asc file should contain a detached signature ONLY. It should not contain a private key. Can you elaborate more about this issue?

OS201 skycruiser8

**Comment by aceyoga** [comment]
Hello @ikaustubhk ,
Thank you for the warning. The file consists of a digest message from my previous assignments, and i don't think it has a security issue. I have removed the file, just in case.

OS201 aceyoga
